config/routes.rb
Rails.application.routes.draw do
  # get 'favourites/index'
  # get 'favourites/create'
  # get 'favourites/destroy'
  # get 'reviews/new'
  # get 'reviews/create'
  # get 'cars/index'
  # get 'cars/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#index"
  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end
  resources :favourites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :favourites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :brand, presence: true
  validates :model, presence: true
  validates :year, numericality: { only_integer: true }
  validates :fuel, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :nickname, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :comment, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end
  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<div class="container">

  <% @cars.each do |car| %>
    <%= link_to car_path(car) do%>
      <div class="card">
        <h1><%=  car.brand %></h1>
        <h3><%= car.model  %></h3>
        <p><%= car.created_at.strftime('%e %b %Y %H:%M:%S%p') %></p>
        <%= image_tag(car.image_url) %>
        <%= link_to  car_path(car) do%>
        <div class="footer">
          <div class="d-flex align-items-center">
            <i class="fa-regular fa-comment"></i>
            <span> Comment</span>
          </div>
        <% end %>
          <div class="owner">
            <p><%= car.owner.nickname %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to 'My Garage', favourites_path %>

app/views/cars/show.html.erb
<div class="container">
  <div class="card">
    <%= image_tag(@car.image_url) %>
    <div class="main">
      <div class= "car-info">
        <h1><%= @car.brand %> </h1>
        <h2><%= @car.model %></h2>
        <p><%= @car.fuel %></p>
        <p><%= @car.year %></p>
      </div>
      <div class="user-actions">
        <div class="favourite">
          <% if  @car.favourites.empty?%>
            <%= simple_form_for [@car, @favourite] do |f| %>
              <%= f.submit 'Save to my Garage', class: 'btn btn-danger' %>
            <% end %>
          <% else %>
            <p> Already parked in Garage</p>
          <% end %>
        </div>
        <div class="comment">
          <%= simple_form_for [@car, @review] do |f| %>
          <%= f.input :comment, placeholder: "commnet here" %>
          <%= f.input :rating, collection: 1..5 %>

          <%= f.submit "Send", class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>

    <% @car.reviews.each do |review| %>
    <div class="d-flex ms-4">
      <p><%= review.comment %></p>
      <p><%= '⭐' * review.rating %></p>
    </div>
     <hr>
    </div>
    <% end %>

  </div>
</div>

app/views/favourites/index.html.erb
<div class="car">
  <h1>My Garage</h1>

  <% @favourites.each do |favourite| %>
    <div class="car-info">
      <div class="car-details">
        <div class="image">
          <%= image_tag(favourite.car.image_url) %>
        </div>
        <div class="heading">
          <h2><%= favourite.car.brand %></h2>
          <h3> <%= favourite.car.model %> </h3>
          <p> <%= favourite.car.year %>  | <%= favourite.car.fuel %></p>
        </div>
      </div>
        <%= link_to  favourite_path(favourite),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if controller.controller_name != 'pages' %>
      <%= render '/shared/navbar' %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/27703376/pexels-photo-27703376/free-photo-of-white-cars-in-garage.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1);">
  <div class="container">
    <h1> Awesome garage</h1>
    <h6>Your personal <strong>Garage</strong> with the <strong>Cars</strong> of your dreams </h6>
    <%= link_to 'Enter', cars_path, class: 'btn'%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar mt-6">
  <div class= "logo">
  <%= image_tag 'garage_logo.png' %>
    Awesome Garage</div>
  <div class= "navbar_links">
    <%= link_to 'Home', cars_path %>
    <%= link_to 'My Garage', favourites_path %>
  </div>

</div>